version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # Główna ścieżka projektu
    schedule:
      interval: "daily"  # Aktualizacje raz w tygodniu
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "react"
        versions: ["18.x"]  # Pomija aktualizacje Reacta do wersji 18.x

