version: 2
updates:
  - package-ecosystem: "pip"
    directory: "MaceWindu/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "fix(dependancies)"
    labels:
      - "dependencies"